
USE EMPRESA

INSERT INTO PESSOA(nomePessoa,CNH)
VALUES ('LUCAS','213123'),('ALFREDO','23423')

INSERT INTO	TELEFONE(idPessoa, numeroTelefone)
VALUES (1,'11922222222'),(2,'11933333333')

INSERT INTO EMAIL (idPessoa,enderecoEmail)
VALUES (1,'LUCAS@LUCAS.COM'),
       (2,'ALFREDO@HOTMAIL.COM')

SELECT * FROM PESSOA
SELECT * FROM TELEFONE
SELECT * FROM EMAIL 